package install

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/blamely/blamely/internal/config"
)

// InstallGitHook sets core.hooksPath to ~/.blamely/git-hooks (globally) and
// writes a post-commit script that invokes `blamely attribute` and then chains
// to any repo-local .git/hooks/post-commit. Returns the previous value of
// core.hooksPath (empty if unset).
func InstallGitHook(binaryPath string) (priorHooksPath string, hadPrior bool, err error) {
	hooksDir, err := config.GitHooksDir()
	if err != nil {
		return "", false, err
	}
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return "", false, fmt.Errorf("mkdir %s: %w", hooksDir, err)
	}

	priorHooksPath, hadPrior = readGlobalConfig("core.hooksPath")

	scriptPath := filepath.Join(hooksDir, postCommitName())
	if err := writePostCommitScript(scriptPath, binaryPath); err != nil {
		return priorHooksPath, hadPrior, err
	}

	prePushPath := filepath.Join(hooksDir, "pre-push")
	if err := writePrePushScript(prePushPath); err != nil {
		return priorHooksPath, hadPrior, err
	}

	if err := setGlobalConfig("core.hooksPath", hooksDir); err != nil {
		return priorHooksPath, hadPrior, err
	}
	return priorHooksPath, hadPrior, nil
}

// UninstallGitHook restores the previous core.hooksPath (or unsets it if there
// was none), then removes our hooks dir.
func UninstallGitHook(prior string, hadPrior bool) error {
	if hadPrior {
		if err := setGlobalConfig("core.hooksPath", prior); err != nil {
			return err
		}
	} else {
		_ = unsetGlobalConfig("core.hooksPath")
	}
	dir, err := config.GitHooksDir()
	if err != nil {
		return err
	}
	return os.RemoveAll(dir)
}

func postCommitName() string {
	if runtime.GOOS == "windows" {
		// Git for Windows runs hooks in MSYS bash; the file is still named
		// `post-commit` without an extension.
		return "post-commit"
	}
	return "post-commit"
}

// writePostCommitScript renders a small shell script that:
//   1. Calls `blamely attribute <repo> <sha>` (best-effort, never blocks the commit).
//   2. Chains to a repo-local .git/hooks/post-commit if one exists.
func writePostCommitScript(path, binaryPath string) error {
	// We resolve the repo via `git rev-parse --show-toplevel` inside the script
	// so the same hook works for every repo on this machine.
	// The script:
	//   - Exits 0 if the binary is missing or `git rev-parse` fails, so a
	//     broken Blamely never blocks a user's commit.
	//   - Runs `blamely attribute` in the foreground (it's fast: reads SQLite
	//     and writes a git note) so the colored AI/Human bar prints inline.
	//   - Chains to a repo-local .git/hooks/post-commit afterwards, because
	//     core.hooksPath is global and we don't want to shadow user hooks.
	script := fmt.Sprintf(`#!/bin/sh
# Generated by Blamely. Do not edit by hand.
# Reverse via:  blamely uninstall

BLAMELY=%q
if [ ! -x "$BLAMELY" ]; then
    # 1. Try the stable install location under ~/.blamely/bin/.
    STABLE="$HOME/.blamely/bin/blamely"
    if [ -x "$STABLE" ]; then
        BLAMELY="$STABLE"
    elif command -v blamely >/dev/null 2>&1; then
        # 2. Fall back to whatever is on $PATH.
        BLAMELY=$(command -v blamely)
    else
        # 3. Binary not found anywhere — skip silently so the commit is
        #    never blocked. Run "blamely install" to repair.
        exit 0
    fi
fi

SHA=$(git rev-parse HEAD 2>/dev/null) || exit 0
REPO=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0

# Synchronous: attribute is fast (SQLite read + git diff + git notes add).
# Output flows to the terminal so the user sees the AI/Human bar after committing.
"$BLAMELY" attribute "$REPO" "$SHA" || true

# Chain to a repo-local hook if present (we hijacked core.hooksPath).
# Skip the chain if the local hook is a legacy blamely-cli / blamely managed
# script — we've already handled attribution above, running it again would
# call a stale binary and show a confusing error.
REPO_HOOK="$REPO/.git/hooks/post-commit"
if [ -x "$REPO_HOOK" ]; then
    if grep -q "blamely" "$REPO_HOOK" 2>/dev/null; then
        # Looks like a blamely-managed hook — skip to avoid double-run or
        # stale-binary errors from an old blamely-cli installation.
        exit 0
    fi
    exec "$REPO_HOOK" "$@"
fi
exit 0
`, binaryPath)

	if err := atomicWrite(path, []byte(script), 0o755); err != nil {
		return err
	}
	return nil
}

// writePrePushScript renders a shell script that pushes refs/notes/blamely to
// the same remote the user is pushing to, then chains to any repo-local
// .git/hooks/pre-push. The notes push is best-effort and never blocks the push.
func writePrePushScript(path string) error {
	script := `#!/bin/sh
# Generated by Blamely. Do not edit by hand.
# Reverse via:  blamely uninstall

REMOTE="$1"

# Forward stdin to the chained hook (if any); buffer it first since we may
# need to pass it along after consuming it ourselves.
STDIN=$(cat)

# Push attribution notes to the same remote — silently ignore errors (remote
# may not accept notes refs, or there may be no notes yet).
git push "$REMOTE" refs/notes/blamely 2>/dev/null || true

# Chain to a repo-local pre-push hook if present.
REPO=$(git rev-parse --show-toplevel 2>/dev/null) || { printf '%s\n' "$STDIN"; exit 0; }
REPO_HOOK="$REPO/.git/hooks/pre-push"
if [ -x "$REPO_HOOK" ]; then
    printf '%s\n' "$STDIN" | exec "$REPO_HOOK" "$@"
fi
exit 0
`
	return atomicWrite(path, []byte(script), 0o755)
}

func readGlobalConfig(key string) (value string, present bool) {
	out, err := exec.Command("git", "config", "--global", "--get", key).Output()
	if err != nil {
		// `git config --get` exits 1 when the key isn't set.
		var ee *exec.ExitError
		if errors.As(err, &ee) && ee.ExitCode() == 1 {
			return "", false
		}
		return "", false
	}
	return strings.TrimSpace(string(out)), true
}

func setGlobalConfig(key, value string) error {
	cmd := exec.Command("git", "config", "--global", key, value)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git config --global %s %q: %v (%s)", key, value, err, strings.TrimSpace(stderr.String()))
	}
	return nil
}

func unsetGlobalConfig(key string) error {
	cmd := exec.Command("git", "config", "--global", "--unset", key)
	// Exit code 5 = "no such variable" — fine.
	if err := cmd.Run(); err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) && (ee.ExitCode() == 5 || ee.ExitCode() == 1) {
			return nil
		}
		return err
	}
	return nil
}
