package install

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// initRepo creates a real git repo in a temp dir and returns its root.
func initRepo(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	cmd := exec.Command("git", "init", "-q", root)
	if err := cmd.Run(); err != nil {
		t.Skipf("git init unavailable: %v", err)
	}
	return root
}

func TestRemoveLegacyRepoHooks_RemovesBlamelyArtifacts(t *testing.T) {
	root := initRepo(t)
	gitDir := filepath.Join(root, ".git")

	// Legacy per-repo runner directory + a Blamely-managed pre-push hook.
	runnerDir := filepath.Join(gitDir, "blamely")
	if err := os.MkdirAll(runnerDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(runnerDir, "hookRunner-pre-push.sh"), []byte("#!/bin/sh\ngit push \"$1\" refs/notes/blamely\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	prePush := filepath.Join(gitDir, "hooks", "pre-push")
	if err := os.WriteFile(prePush, []byte("#!/bin/sh\n# Blamely hookRunner (start)\ngit push \"$1\" refs/notes/blamely\n"), 0o755); err != nil {
		t.Fatal(err)
	}

	RemoveLegacyRepoHooks(root)

	if _, err := os.Stat(runnerDir); !os.IsNotExist(err) {
		t.Errorf(".git/blamely should have been removed, stat err=%v", err)
	}
	if _, err := os.Stat(prePush); !os.IsNotExist(err) {
		t.Errorf("Blamely-managed pre-push should have been removed, stat err=%v", err)
	}
}

func TestRemoveLegacyRepoHooks_PreservesUserHooks(t *testing.T) {
	root := initRepo(t)
	gitDir := filepath.Join(root, ".git")

	// A user's own pre-push hook that merely mentions blamely in a comment must
	// NOT be deleted — we never override user configuration.
	userHook := filepath.Join(gitDir, "hooks", "pre-push")
	userBody := []byte("#!/bin/sh\n# my lint gate; also see blamely docs\nnpm run lint\n")
	if err := os.WriteFile(userHook, userBody, 0o755); err != nil {
		t.Fatal(err)
	}

	RemoveLegacyRepoHooks(root)

	got, err := os.ReadFile(userHook)
	if err != nil {
		t.Fatalf("user hook should still exist: %v", err)
	}
	if string(got) != string(userBody) {
		t.Errorf("user hook was modified:\n%s", got)
	}
}

func TestIsBlamelyManagedHook(t *testing.T) {
	dir := t.TempDir()
	cases := []struct {
		name string
		body string
		want bool
	}{
		{"generated marker", "#!/bin/sh\n# Generated by Blamely.\n", true},
		{"runner marker", "#!/bin/sh\n# Blamely hookRunner (pre-push)\n", true},
		{"notes ref marker", "#!/bin/sh\ngit push \"$1\" refs/notes/blamely\n", true},
		{"user hook mentioning blamely", "#!/bin/sh\n# see blamely\nmake test\n", false},
		{"plain user hook", "#!/bin/sh\nmake test\n", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			p := filepath.Join(dir, tc.name)
			if err := os.WriteFile(p, []byte(tc.body), 0o644); err != nil {
				t.Fatal(err)
			}
			if got := isBlamelyManagedHook(p); got != tc.want {
				t.Errorf("isBlamelyManagedHook=%v, want %v", got, tc.want)
			}
		})
	}
	if isBlamelyManagedHook(filepath.Join(dir, "does-not-exist")) {
		t.Error("missing file should not be reported as managed")
	}
}
